edition = "2015"
fn_args_layout = "Vertical"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
max_width = 98
reorder_modules = false
use_small_heuristics = "Max"

unstable_features = true
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
control_brace_style = "ClosingNextLine"
combine_control_expr = false
comment_width = 98
enum_discrim_align_threshold = 60
error_on_line_overflow = true
error_on_unformatted = true
format_strings = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
match_arm_blocks = false
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
spaces_around_ranges = true
struct_field_align_threshold = 40
version = "Two"
where_single_line = true
wrap_comments = true
